language: groovy
jdk:
- openjdk7
sudo: false
cache:
  directories:
  - $HOME/.gradle
before_script:
- rm -rf target
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: Jv7h5a516QUzPzfYNKxz41+hSXMOhoGeUhglx/UzXwrsVncH1qKpDrBV+cJkGNMA83+vXjumwlIGKO0GzYAnem1ICSzAbTecv3VSXVX+2hjrU9gxB8C3Os1pBlt04ds06yWibTOAIaSXyH8a9c6E2K2xWOKxSQ9BcjB1yP3BMAA=
  - secure: EqXC1PCc1o6OCIJdT8p+6WGD2pROnp8Tb8H8zpCrUe+rAzVkhr9Jw/jMymI4i75MQCHcIA7/mM3fwJCSXqxk6ch3+KwIdfX9Ldph8WIIOs/mT7uOsMirOSvpyJCDwoguOGQVA8rWEVymemL+GlpNOjE/u/mhYQ+mIgEdyBN6cfo=
  - secure: QuP+ODiBJn8whRrDsIdRBSJ+GOxq8KF8ClZgr2oDKnYTPB1uoCFvvit3TXWLp/fdB1ABjJoq+hLW2KPai7B7FdqX7y30m73ZLUekAgVei5z2f14I5uTS72fnc96ANUvwX7yycLkiyeZ4GG6LlbgFqNzTRErP7UO5FYe7CLqGF/Y=
  - secure: BkU9dYTqM3AD9NmAK+8C/1o1k/ydoCIpGw80qZf8dZ575yDLkbkvJcTdIH+LQNeg/3T3lWq62FeDxntpR1WhX6IOdVk+xixk6s2t+RQtwB3XuIL04HmXGH6v4UCue9ZUctMcvipstXQOjzShgMqZ69BzjmTkkMFv+sig9Wbg/VQ=
  - secure: Oah5iuizLISjWK8J19idP/Yo71CpY83P/3azNJ4fwKBSLaKKDFgF0OhxrzgN9t5Da/q3fkzeevFoTspZjUUtj122UioIXt0U0R4gI1r4dyPG9j0gJ0RL/nGIOIs6FZmJdrnBvCr5+p6BxUG3oVNArXBTjnfmaamFdZsja0N2ifQ=
  - secure: VwkaJeu6znmAUbPjnbgyuRh62Jrji/WplzXoplhebQ5PupuhB2iA1YCowTLjk+/uDqk8qOTzr3zRuROlwZT08JN3elxVz30HkirwlXLKWlja3Fg7/I+Jm3NkrJYalefKCSpQnzVTTJwa0d+jOnMT+VtSfBqvC76VvZlEH0z7LEA=
  - secure: fyOkoihacSQjQcXF4nxtg/9WL0OCFzfQxBcVRGO9FL4fCcEmy4s7rDyu9gkJTCK9OGqQdAD0cRnBQmYny8GhErsudvglCskOO/1xE/wQJqEh8ZwI67kbLwkeBriKVIjRR47aMBDaINoF/9uuDovzsexwydJxDWSgATk6l5/UqHc=
deploy:
  provider: releases
  api_key:
    secure: m7e4FuggqcA7DnyBCpPnrO4UZ1fDU0Eg9KlN2r0yifRfdxMdOcNNFfDdaEiJAuXJTjxoaBCgXQu3ALHHLkSeaAACkHDPxwmbba3KRYS757Z7jjYU8DLprj7m1iWecVu5Iccl1i2RUZcjZU4uVgnFC4UFuXZ/e9yM8/qLATshA8Y=
  file: build/libs/geb-${TRAVIS_TAG:1}.jar
  on:
    repo: grails3-plugins/geb
    tags: true
    all_branches: true
