language: groovy
jdk:
- openjdk8
- openjdk11
install: true
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script: "./travis-build.sh"
deploy:
  provider: releases
  api_key:
    secure: m7e4FuggqcA7DnyBCpPnrO4UZ1fDU0Eg9KlN2r0yifRfdxMdOcNNFfDdaEiJAuXJTjxoaBCgXQu3ALHHLkSeaAACkHDPxwmbba3KRYS757Z7jjYU8DLprj7m1iWecVu5Iccl1i2RUZcjZU4uVgnFC4UFuXZ/e9yM8/qLATshA8Y=
  file: build/libs/geb-${TRAVIS_TAG:1}.jar
  on:
    repo: grails3-plugins/geb
    tags: true
    all_branches: true
env:
  global:
  - secure: CeGK9pfTG6Okg0KCdksgflnNm2pY6thPLFlVWYOGIHy946rXMrxG1nC58ug7oY8Ng/BxppDrV9YkD6Z5wPc8ZtA+/pOQL4MZlseeJUOTxwx9feWFLEd2p338t9BGJbP+7GrOKCkPTiJBAOQhn/WyM+jpfmTAc5E6nteMWDyAVt4=
  - secure: Dym0gTvDOPy4M83WLWmNngKQa23QqE6sZBgoIgFUx3ipLvb4aZH8Q9AsVhaj/HsC+9S8/a+N2Ked9aVq8oVq13bIHXNGvmI5ecZoUXGtRKXP+04wTo3XlT94dfJYshs9qirzjI0/l68sh0oXWA3RImUaxKUVtWZnF90MUy8DrsY=
  - secure: SAOYmjyxZ2cOkBpXwn4HGAzgoaRtj+/4djCU1SyEhV20hEOSLHLSXMjlquEkRnGxagF0k0feGz4bJzcyd9NOe6OjLmExC7aR+Sbvwk5URwdjQoVo5KTO2jc2LLapl6GAIShWFWiAY0QcBfzafAPJ/76uQ53LNRfi12ch3kkkkFs=
  - secure: Q6pv7dt4xkzjaoTF8JHlJX++R516cuzZBW42AYXoRSlc3dV0UG92DTF5mvWLfUjn9sOonQCJkxZ1icLyHXwPoZoT8H1O4kG1cGv1EGpwtuJr+isgYMZlrSLOC5DHlVg77JQWPZyJFcnRIjWUOkPuREqbIOw2PwJs6F7iSZ/Bo88=
  - secure: daSeFOmzESIieGsmkZxer3TKww0TK69mfPPI8OUqK7PYb6C22MqhDGzA27CZhdSV7LGtywr2dUIzeRlW/gedhcEjZITbPcR7fRotgMvkqtL3TJ/OFJChyrDghtbVMR1HlQfCfzU5kQlIrIxE8qCiArlveo6ob/HVo8ihk1cv78E=
  - secure: aty9rdoD6E65m7JKZ5iantKpC4aQbkOjeCEocgtW1kaJTrgmE7kflg5wPUn3nLMR9TCDKa7yymYmpXWmQCJGCq4GNPpmKNdIzJDeeQvNOOtoQt7/TJ7l5zHx0BdLS3eTd2xGGH0MCkAt0A6V1WqHsdQcs7od0hqxFogxLBbtndQ=
  - secure: XGMFulG/K7oH9+lqHW/ZibC5DumsLkqeg9S9mwAWsTC4z6OgEBg4cSWme3/DitgxuHllCzVevL3cqaK/oDChGK8lCap1ieKzyIjNpaajTTFvA7JQsCQzDgEBrr5PtzgugCJoMRCkIreila+51A2xOuP8lELv4KWgkpGUIXLxTW8=
  - secure: Ifqn/b+UcC8I96NJOOjP83IPjK2Np/o1tpXBTcT6fEunbBJ1GxiOR1e1pZaqhCK0lzSBOOZIu8LRnuKZ4Y5Hld3gRy0YoO3msQ59FKxLsUatDfw95dRDxxSZjDAppEQzsnnAX9tV1D6fl1qdO4FOOSVXx5Q6/uSIWoNGZ2cYQ3Q=
